# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Variables with address and credentials stored in Azure secrets

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  build_cake: './src/build.cake'
  default_ip: '192.168.50.4'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(Invoke-WebRequest -uri "https://api.ipify.org/").Content'

- task: UseNode@1
  inputs:
    script: '"C:\Program Files\nodejs\npm.cmd" --version'
  displayName: Installing Node 10

- task: DownloadSecureFile@1
  name: license_file
  inputs:
    secureFile: 'license.xml'
  displayName: Download license
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      (Get-Content $(build_cake)) -replace "MSBuildToolVersion.VS201\d{1,3}", $env:agent_buildTools | Set-Content $(build_cake)
      (Get-Content $(build_cake)) -replace "$(default_ip)", $env:HOST_NETWORK_ADDRESS | Set-Content $(build_cake)
      move $(license_file.secureFilePath) ./src/
  displayName: Config preparation

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$False -Force
      # Install-Module -Name CredentialManager -Repository PSGallery -Confirm:$False -Force
      $secure_password = "$(user_password)" | ConvertTo-SecureString -AsPlainText -Force
      # New-StoredCredential -Target $env:HOST_NETWORK_ADDRESS -Username $(user_name) -Password $secure_password
      cmdkey /add:$(HOST_NETWORK_ADDRESS) /user:$(user_name) /pass:$(user_password)
  displayName: Add windows credentials to agent

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'copy ./README.md \\$env:HOST_NETWORK_ADDRESS\c$\inetpub'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'cmdkey /delete:$env:HOST_NETWORK_ADDRESS'
  displayName: Remove windows credentials from agent

#- task: PowerShell@2
#  inputs:
#    filePath: './src/build.ps1'
#    workingDirectory: './src/'