# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Variables with address and credentials stored in Azure secrets

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  build_cake: './src/build.cake'
  default_ip: '192.168.50.4'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #Change IP server address
      (Get-Content $(build_cake)) -replace "$(default_ip)", $(HOST_NETWORK_ADDRESS) | Set-Content $(build_cake)
  displayName: Config preparation

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Test changes
      Get-Content $(build_cake)
  displayName: Result test

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "1"
      Write-Host $env:HOST_NETWORK_ADDRESS
      Write-Host "2"
      Write-Host $(HOST_NETWORK_ADDRESS))